// Gate 0: can the `dsh --profile web` host tree be bundled for workerd, and
// what Node surface does it drag along? Bundles every package row of the web
// composition (base + web-app patch layers) through the workspace resolver
// with workerd conditions, tables each Node builtin with its importers, and
// measures the compressed size against the 10 MiB Worker limit. Writes
// gate0-imports.md beside this app and exits non-zero on any unresolved import.
//
// Run: pnpm --filter @deepseek-ai/dsh-cf-web run gate0
import * as esbuild from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { gzipSync } from 'node:zlib'
import { ROOT, relativeToRoot, workspaceResolver } from './workspace-resolver.mjs'
import { CF_EXCLUDED_ROWS, compositionPackages } from './composition.mjs'

/** Worker compressed-size limit (paid plan), bytes. */
const WORKER_LIMIT_BYTES = 10 * 1024 * 1024

async function bundle(names, label) {
  const builtins = new Map()
  const entry = names.map((name, i) => `import * as m${i} from ${JSON.stringify(name)}\nexport { m${i} }`).join('\n')
  const result = await esbuild.build({
    stdin: { contents: entry, resolveDir: ROOT, loader: 'js' },
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    minify: true,
    mainFields: ['module', 'main'],
    conditions: ['workerd', 'worker', 'import', 'default'],
    metafile: true,
    logLevel: 'silent',
    loader: { '.sql': 'text', '.node': 'empty', '.css': 'text' },
    plugins: [workspaceResolver({
      onBuiltin(specifier, importer) {
        if (!builtins.has(specifier)) builtins.set(specifier, new Set())
        builtins.get(specifier).add(relativeToRoot(importer))
      },
    })],
  })
  const output = result.outputFiles[0].contents
  const gzip = gzipSync(output, { level: 9 }).length
  const byPackage = new Map()
  for (const [file, input] of Object.entries(result.metafile.inputs)) {
    const rel = relativeToRoot(resolve(file))
    const match = /^node_modules\/(@[^/]+\/[^/]+|[^/]+)\//.exec(rel)
    const key = match ? match[1] : rel.split('/').slice(0, 3).join('/')
    byPackage.set(key, (byPackage.get(key) ?? 0) + input.bytes)
  }
  const rows = [...builtins.entries()].sort(([a], [b]) => a.localeCompare(b))
    .map(([spec, importers]) => `| \`${spec}\` | ${[...importers].sort().join('<br>')} |`)
  const largest = [...byPackage.entries()].sort((a, b) => b[1] - a[1]).slice(0, 20)
    .map(([name, bytes]) => `| ${name} | ${(bytes / 1024).toFixed(0)} KiB |`)
  return {
    label,
    errors: result.errors,
    modules: Object.keys(result.metafile.inputs).length,
    bytes: output.length,
    gzip,
    markdown: [
      `## ${label}`,
      '',
      `${names.length} package entries, ${Object.keys(result.metafile.inputs).length} bundled modules, `
        + `${(output.length / 1024 / 1024).toFixed(2)} MiB minified, **${(gzip / 1024 / 1024).toFixed(2)} MiB gzip** `
        + `(limit ${(WORKER_LIMIT_BYTES / 1024 / 1024).toFixed(0)} MiB compressed).`,
      '',
      '| Node builtin | importers |',
      '|---|---|',
      ...rows,
      '',
      '| largest inputs (by package) | size |',
      '|---|---|',
      ...largest,
      '',
    ].join('\n'),
  }
}

const full = compositionPackages()
const target = full.filter(name => !CF_EXCLUDED_ROWS.has(name))
const reports = [
  await bundle(full, 'A. Complete web host tree (every row of base + web-app)'),
  await bundle(target, 'B. CF target composition (A minus the rows the CF packages replace)'),
]
const out = [
  '# Gate 0 — the web host tree on workerd',
  '',
  'Generated by `scripts/gate0.mjs`; importers are built `lib/` files resolved through package `exports` with the `workerd` condition.',
  '',
  ...reports.map(r => r.markdown),
  '## Rows excluded from B',
  '',
  ...[...CF_EXCLUDED_ROWS.entries()].map(([name, why]) => `- \`${name}\` — ${why}`),
  '',
].join('\n')
writeFileSync(join(ROOT, 'apps/cf-web/gate0-imports.md'), out)
for (const report of reports) {
  console.log(`${report.label}: ${report.modules} modules, ${(report.gzip / 1024 / 1024).toFixed(2)} MiB gzip, ${report.errors.length} errors`)
  for (const error of report.errors) console.error(`  ${error.text}`)
}
if (reports.some(r => r.errors.length > 0) || reports.some(r => r.gzip > WORKER_LIMIT_BYTES)) process.exit(1)
